config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'likes/create'

  devise_for :users

  devise_scope :user do
    root 'users#index'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        resources :likes, only: [:create, :destroy]
        resources :comments, only: [:new, :create, :destroy]
      end
    end  
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show], defaults: {format: :json} do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :manage, Comment, author: user
    can :manage, Post, author: user
    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_comments_counter

  private

  def update_post_comments_counter
    post.update_comments_counter
  end
end

app/models/like.rb
# app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_likes_counter

  private

  def update_post_likes_counter
    post.update_likes_counter
  end
end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_create :update_author_posts_count

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end

  private

  def update_author_posts_count
    author.update(posts_count: author.posts.count)
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :password, presence: true

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class Api::V1::CommentsController < ApplicationController
      include RecordNotFoundHandler
      before_action :authenticate_user!

      def index
        user = User.find(params[:user_id])
        post = user.posts.find(params[:post_id])
        comments = post.comments
        render json: comments
      end

      def create
        user = User.find(params[:user_id])
        post = user.posts.find(params[:post_id])
        comment = post.comments.build(comment_params)
        comment.user = user
        if comment.save
          render json: comment, status: :created
        else
          render json: comment.errors, status: :unprocessable_entity
        end
      end

      private

      def comment_params
        params.require(:comment).permit(:text)
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class Api::V1::PostsController < ApplicationController
      include RecordNotFoundHandler
      def index
        user = User.find(params[:user_id])
        posts = user.posts
        render json: posts
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comments_params)
    comment.post = post
    if comment.save
      flash[:success] = 'Successfully commented on this post'
      redirect_to user_post_url(id: params[:post_id])
    else
      flash.now[:error] = 'Error: Post could not be created'
      render user_post_path(id: current_user.id)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(@comment.post_id)
    redirect_to user_path(current_user.id), notice: 'Comment deleted.'
  end

  private

  def comments_params
    params.require(:add_comment).permit(:text)
  end
end

app/controllers/concerns/record_not_found_handler.rb
module RecordNotFoundHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  end

  private

  def record_not_found
    render json: { error: 'Record not found' }, status: :not_found
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    user_like = current_user.likes.new(post:)
    if user_like.save
      flash[:success] = 'You liked this post'
      redirect_to user_post_url(id: params[:post_id])
    else
      flash.now[:error] = 'Error: Post could not be created'
      render user_post_path(id: current_user.id)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts).find(params[:user_id])
  end

  def show
    @post = User.includes(posts: [:author]).find(params[:user_id]).posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    new_post = current_user.posts.new(post_params)
    new_post.comments_counter = 0
    new_post.likes_counter = 0
    @post = new_post

    respond_to do |format|
      if new_post.save
        format.html do
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_url
        end
      else
        format.html do
          flash.now[:error] = 'Error: Post could not be created'
          render :new
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    Comment.where(post_id: @post.id).destroy_all
    Like.where(post_id: @post.id).destroy_all
    @post.destroy
    flash[:success] = 'You deleted this post'
    redirect_to user_path(@post.author), notice: 'Post Deleted!'
  end

  private

  def post_params
    params.require(:add_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < DeviseController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.html.erb
<div class="form-container">
<%= form_with model: @comment, url: user_post_comments_path(post_id: @post.id), method: :post, local: true, scope: :add_comment do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text, size: "100x6" %>
  </div>

  <%= form.submit %>
<% end %>

<% flash.each do |name, msg| -%>
  <%= content_tag :span, msg, class: name %>
<% end -%>
</div>

app/views/comments/new.html.erb
<div class="form-container">
<%= form_with model: @comment, url: user_post_comments_path(post_id: @post.id), method: :post, local: true, scope: :add_comment do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text, size: "100x6" %>
  </div>

  <%= form.submit %>
<% end %>

<% flash.each do |name, msg| -%>
  <%= content_tag :span, msg, class: name %>
<% end -%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-brand">
    <%= link_to "Blog App", root_path, class: "navbar-item" %>
  </div>

  <div class="navbar-menu">
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="dropbtn"><%= current_user.email %> ▼</button>
          <div class="dropdown-content">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-link" %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item">
          <div class="navbar-link-group">
            <%= link_to "Sign In", new_user_session_path, class: "navbar-link" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "navbar-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="dropdown.js"></script>
  </head>

  <body>
    <%= render template='layouts/navbar' %>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<%= link_to(user_post_path(@user, post)) do%>
  <div class="comment-div border-style user-posts">
    <div class="comment-text">
      <h3>Post <%= post_counter + 1 %></h3>
      <p><%= post.text %></p>
    </div>
    <div class="counter-div d-flex">
      <span>Comments: <%= post.comments_counter%></span>
      <span>Likes: <%= post.likes_counter%></span>
    </div>
  </div>
<% end %>

app/views/posts/create.html.erb
<div class="form-container form-container-margin">
  <%= form_with model: @post, url: user_posts_path(user_id: current_user.id), method: :post, local: true, scope: :add_post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :text %><br>
      <%= form.text_area :text, size: "80x6" %>
    </div>

    <%= form.submit %>
  <% end %>

  <% flash.each do |name, msg| -%>
    <%= content_tag :span, msg, class: name %>
  <% end -%>
</div>

app/views/posts/index.html.erb
<div class="bio-div">
  <%= render @user %>
</div>
<div class="bio-div">
  <% @user.posts.each_with_index do |post, index|%>
    <div class="comment-bio-div">
      <%= render partial: "post", locals: { post_counter: index, post: post } %>
    </div>
    <div class="comments-section border-style">
      <% post.recent_comments.each do |comment|%>
        <p class="d-flex"><span><%= comment.author.name %>:</span><span><%= comment.text %></span></p>
      <% end %>
    </div>
  <% end %>
</div>
<div class="post-btn-div d-flex">
    <button class="posts-btn border-style">Pagination</button>
</div>

app/views/posts/new.html.erb
<div class="form-container form-container-margin">
  <%= form_with model: @post, url: user_posts_path(user_id: current_user.id), method: :post, local: true, scope: :add_post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :text %><br>
      <%= form.text_area :text, size: "80x6" %>
    </div>

    <%= form.submit %>
  <% end %>

  <% flash.each do |name, msg| -%>
    <%= content_tag :span, msg, class: name %>
  <% end -%>
</div>

app/views/posts/show.html.erb
<div class="post-details-div">
  <div class="single-post-details border-style">
    <div class="title-details d-flex">
      <% if can? :destroy, @post %>
        <%= button_to "Delete this post", user_post_path(@post.author, @post), method: :delete, class: "delete-button" %>
      <%end%>
      <p><%= @post.title %> by <%= @post.author.name%></p>
      <div>
        <span>Comments: <%= @post.comments_counter%></span>
        <span>Likes: <%= @post.likes_counter%></span>
      </div>
    </div>
    <div>
      <%= @post.text %>
      <%= form_with url: user_post_likes_path(@post.author, @post), method: :post, local: true do |form| %>
        <%= form.button type: :submit, class: 'link-button' do %>
          <span class="heart-icon">&#x2665;</span>
        <% end %>
      <% end %>    
    </div>   
  </div>
  
  <div class="comments-section border-style">
    <% @post.recent_comments.each do |comment|%>
      <p class="d-flex">
        <span><%= comment.author.name %>:</span>
        <span><%= comment.text %></span>
        <span>
          <% if can? :delete, comment %>
            <%= button_to "Delete this comment", user_post_comment_path(comment.author, comment.post, comment), method: :delete, class: "delete-button" %>
          <%end%>
        </span>
      </p>
    <% end %>
  </div>
<%= render template: 'comments/new', post_id: @post.id %>
</div>

app/views/users/_user.html.erb
<%= link_to(user) do %>
<article class="container d-flex">
  <div class="img-container border-style">
    <img src="<%= user.photo %>" alt="<%= user.name  %>'s Photo" class="profile">
  </div>
  <div class="user-details d-flex border-style">
    <h1 class="user-name"><%= user.name %></h1>
    <p class="number-of-posts">Number of Posts: <%= user.posts_count %></p>
  </div>
</article>
<% end %>

app/views/users/index.html.erb
  <div>
    <%= render @users %>
  </div>

app/views/users/show.html.erb
<section>
  <div>
    <%= render @user %>
  </div>
  <div class="bio-div">
    <div class="bio-details border-style">
      <h3>Bio</h3>
      <p class="user-bio">
        <%= @user.bio%>
      </p>
    </div>
    <div>
      <%= render partial: "posts/post", collection: @user.posts %>
    </div>
  </div>
  <%= render template: 'posts/new', collection: @user.posts %>
  <div class="post-btn-div d-flex">
    <button class="posts-btn border-style">
      <%= link_to 'See All Posts', user_posts_path(@user.id) %>
    </button>
  </div>
</section>